/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DestinosRouteRouteImport } from './routes/destinos/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinosIndexRouteImport } from './routes/destinos/index'
import { Route as DestinosDestinoIdRouteImport } from './routes/destinos/$destinoId'
import { Route as ProtectedViajesRouteRouteImport } from './routes/_protected/viajes/route'
import { Route as ProtectedReservasRouteRouteImport } from './routes/_protected/reservas/route'
import { Route as ProtectedPerfilRouteRouteImport } from './routes/_protected/perfil/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedViajesCompletadosRouteImport } from './routes/_protected/viajes/completados'
import { Route as ProtectedViajesCanceladosRouteImport } from './routes/_protected/viajes/cancelados'
import { Route as ProtectedViajesActivosRouteImport } from './routes/_protected/viajes/activos'
import { Route as ProtectedReservasPagoRouteImport } from './routes/_protected/reservas/pago'
import { Route as ProtectedReservasNaveRouteImport } from './routes/_protected/reservas/nave'
import { Route as ProtectedReservasFechasRouteImport } from './routes/_protected/reservas/fechas'
import { Route as ProtectedReservasConfirmacionRouteImport } from './routes/_protected/reservas/confirmacion'
import { Route as ProtectedReservasCabinaRouteImport } from './routes/_protected/reservas/cabina'
import { Route as ProtectedPerfilSeguridadRouteImport } from './routes/_protected/perfil/seguridad'
import { Route as ProtectedPerfilResumenRouteImport } from './routes/_protected/perfil/resumen'
import { Route as ProtectedAdminResumenRouteImport } from './routes/_protected/admin/resumen'
import { Route as ProtectedAdminPlanetasRouteImport } from './routes/_protected/admin/planetas'
import { Route as ProtectedAdminPasajerosRouteImport } from './routes/_protected/admin/pasajeros'
import { Route as ProtectedAdminNavesRouteImport } from './routes/_protected/admin/naves'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinosRouteRoute = DestinosRouteRouteImport.update({
  id: '/destinos',
  path: '/destinos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinosIndexRoute = DestinosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DestinosRouteRoute,
} as any)
const DestinosDestinoIdRoute = DestinosDestinoIdRouteImport.update({
  id: '/$destinoId',
  path: '/$destinoId',
  getParentRoute: () => DestinosRouteRoute,
} as any)
const ProtectedViajesRouteRoute = ProtectedViajesRouteRouteImport.update({
  id: '/viajes',
  path: '/viajes',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedReservasRouteRoute = ProtectedReservasRouteRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPerfilRouteRoute = ProtectedPerfilRouteRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedViajesCompletadosRoute =
  ProtectedViajesCompletadosRouteImport.update({
    id: '/completados',
    path: '/completados',
    getParentRoute: () => ProtectedViajesRouteRoute,
  } as any)
const ProtectedViajesCanceladosRoute =
  ProtectedViajesCanceladosRouteImport.update({
    id: '/cancelados',
    path: '/cancelados',
    getParentRoute: () => ProtectedViajesRouteRoute,
  } as any)
const ProtectedViajesActivosRoute = ProtectedViajesActivosRouteImport.update({
  id: '/activos',
  path: '/activos',
  getParentRoute: () => ProtectedViajesRouteRoute,
} as any)
const ProtectedReservasPagoRoute = ProtectedReservasPagoRouteImport.update({
  id: '/pago',
  path: '/pago',
  getParentRoute: () => ProtectedReservasRouteRoute,
} as any)
const ProtectedReservasNaveRoute = ProtectedReservasNaveRouteImport.update({
  id: '/nave',
  path: '/nave',
  getParentRoute: () => ProtectedReservasRouteRoute,
} as any)
const ProtectedReservasFechasRoute = ProtectedReservasFechasRouteImport.update({
  id: '/fechas',
  path: '/fechas',
  getParentRoute: () => ProtectedReservasRouteRoute,
} as any)
const ProtectedReservasConfirmacionRoute =
  ProtectedReservasConfirmacionRouteImport.update({
    id: '/confirmacion',
    path: '/confirmacion',
    getParentRoute: () => ProtectedReservasRouteRoute,
  } as any)
const ProtectedReservasCabinaRoute = ProtectedReservasCabinaRouteImport.update({
  id: '/cabina',
  path: '/cabina',
  getParentRoute: () => ProtectedReservasRouteRoute,
} as any)
const ProtectedPerfilSeguridadRoute =
  ProtectedPerfilSeguridadRouteImport.update({
    id: '/seguridad',
    path: '/seguridad',
    getParentRoute: () => ProtectedPerfilRouteRoute,
  } as any)
const ProtectedPerfilResumenRoute = ProtectedPerfilResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => ProtectedPerfilRouteRoute,
} as any)
const ProtectedAdminResumenRoute = ProtectedAdminResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminPlanetasRoute = ProtectedAdminPlanetasRouteImport.update({
  id: '/planetas',
  path: '/planetas',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminPasajerosRoute = ProtectedAdminPasajerosRouteImport.update({
  id: '/pasajeros',
  path: '/pasajeros',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminNavesRoute = ProtectedAdminNavesRouteImport.update({
  id: '/naves',
  path: '/naves',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/destinos': typeof DestinosRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/perfil': typeof ProtectedPerfilRouteRouteWithChildren
  '/reservas': typeof ProtectedReservasRouteRouteWithChildren
  '/viajes': typeof ProtectedViajesRouteRouteWithChildren
  '/destinos/$destinoId': typeof DestinosDestinoIdRoute
  '/destinos/': typeof DestinosIndexRoute
  '/admin/naves': typeof ProtectedAdminNavesRoute
  '/admin/pasajeros': typeof ProtectedAdminPasajerosRoute
  '/admin/planetas': typeof ProtectedAdminPlanetasRoute
  '/admin/resumen': typeof ProtectedAdminResumenRoute
  '/perfil/resumen': typeof ProtectedPerfilResumenRoute
  '/perfil/seguridad': typeof ProtectedPerfilSeguridadRoute
  '/reservas/cabina': typeof ProtectedReservasCabinaRoute
  '/reservas/confirmacion': typeof ProtectedReservasConfirmacionRoute
  '/reservas/fechas': typeof ProtectedReservasFechasRoute
  '/reservas/nave': typeof ProtectedReservasNaveRoute
  '/reservas/pago': typeof ProtectedReservasPagoRoute
  '/viajes/activos': typeof ProtectedViajesActivosRoute
  '/viajes/cancelados': typeof ProtectedViajesCanceladosRoute
  '/viajes/completados': typeof ProtectedViajesCompletadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/perfil': typeof ProtectedPerfilRouteRouteWithChildren
  '/reservas': typeof ProtectedReservasRouteRouteWithChildren
  '/viajes': typeof ProtectedViajesRouteRouteWithChildren
  '/destinos/$destinoId': typeof DestinosDestinoIdRoute
  '/destinos': typeof DestinosIndexRoute
  '/admin/naves': typeof ProtectedAdminNavesRoute
  '/admin/pasajeros': typeof ProtectedAdminPasajerosRoute
  '/admin/planetas': typeof ProtectedAdminPlanetasRoute
  '/admin/resumen': typeof ProtectedAdminResumenRoute
  '/perfil/resumen': typeof ProtectedPerfilResumenRoute
  '/perfil/seguridad': typeof ProtectedPerfilSeguridadRoute
  '/reservas/cabina': typeof ProtectedReservasCabinaRoute
  '/reservas/confirmacion': typeof ProtectedReservasConfirmacionRoute
  '/reservas/fechas': typeof ProtectedReservasFechasRoute
  '/reservas/nave': typeof ProtectedReservasNaveRoute
  '/reservas/pago': typeof ProtectedReservasPagoRoute
  '/viajes/activos': typeof ProtectedViajesActivosRoute
  '/viajes/cancelados': typeof ProtectedViajesCanceladosRoute
  '/viajes/completados': typeof ProtectedViajesCompletadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/destinos': typeof DestinosRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/perfil': typeof ProtectedPerfilRouteRouteWithChildren
  '/_protected/reservas': typeof ProtectedReservasRouteRouteWithChildren
  '/_protected/viajes': typeof ProtectedViajesRouteRouteWithChildren
  '/destinos/$destinoId': typeof DestinosDestinoIdRoute
  '/destinos/': typeof DestinosIndexRoute
  '/_protected/admin/naves': typeof ProtectedAdminNavesRoute
  '/_protected/admin/pasajeros': typeof ProtectedAdminPasajerosRoute
  '/_protected/admin/planetas': typeof ProtectedAdminPlanetasRoute
  '/_protected/admin/resumen': typeof ProtectedAdminResumenRoute
  '/_protected/perfil/resumen': typeof ProtectedPerfilResumenRoute
  '/_protected/perfil/seguridad': typeof ProtectedPerfilSeguridadRoute
  '/_protected/reservas/cabina': typeof ProtectedReservasCabinaRoute
  '/_protected/reservas/confirmacion': typeof ProtectedReservasConfirmacionRoute
  '/_protected/reservas/fechas': typeof ProtectedReservasFechasRoute
  '/_protected/reservas/nave': typeof ProtectedReservasNaveRoute
  '/_protected/reservas/pago': typeof ProtectedReservasPagoRoute
  '/_protected/viajes/activos': typeof ProtectedViajesActivosRoute
  '/_protected/viajes/cancelados': typeof ProtectedViajesCanceladosRoute
  '/_protected/viajes/completados': typeof ProtectedViajesCompletadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/destinos'
    | '/login'
    | '/registro'
    | '/admin'
    | '/perfil'
    | '/reservas'
    | '/viajes'
    | '/destinos/$destinoId'
    | '/destinos/'
    | '/admin/naves'
    | '/admin/pasajeros'
    | '/admin/planetas'
    | '/admin/resumen'
    | '/perfil/resumen'
    | '/perfil/seguridad'
    | '/reservas/cabina'
    | '/reservas/confirmacion'
    | '/reservas/fechas'
    | '/reservas/nave'
    | '/reservas/pago'
    | '/viajes/activos'
    | '/viajes/cancelados'
    | '/viajes/completados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/registro'
    | '/admin'
    | '/perfil'
    | '/reservas'
    | '/viajes'
    | '/destinos/$destinoId'
    | '/destinos'
    | '/admin/naves'
    | '/admin/pasajeros'
    | '/admin/planetas'
    | '/admin/resumen'
    | '/perfil/resumen'
    | '/perfil/seguridad'
    | '/reservas/cabina'
    | '/reservas/confirmacion'
    | '/reservas/fechas'
    | '/reservas/nave'
    | '/reservas/pago'
    | '/viajes/activos'
    | '/viajes/cancelados'
    | '/viajes/completados'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/destinos'
    | '/login'
    | '/registro'
    | '/_protected/admin'
    | '/_protected/perfil'
    | '/_protected/reservas'
    | '/_protected/viajes'
    | '/destinos/$destinoId'
    | '/destinos/'
    | '/_protected/admin/naves'
    | '/_protected/admin/pasajeros'
    | '/_protected/admin/planetas'
    | '/_protected/admin/resumen'
    | '/_protected/perfil/resumen'
    | '/_protected/perfil/seguridad'
    | '/_protected/reservas/cabina'
    | '/_protected/reservas/confirmacion'
    | '/_protected/reservas/fechas'
    | '/_protected/reservas/nave'
    | '/_protected/reservas/pago'
    | '/_protected/viajes/activos'
    | '/_protected/viajes/cancelados'
    | '/_protected/viajes/completados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  DestinosRouteRoute: typeof DestinosRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinos': {
      id: '/destinos'
      path: '/destinos'
      fullPath: '/destinos'
      preLoaderRoute: typeof DestinosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinos/': {
      id: '/destinos/'
      path: '/'
      fullPath: '/destinos/'
      preLoaderRoute: typeof DestinosIndexRouteImport
      parentRoute: typeof DestinosRouteRoute
    }
    '/destinos/$destinoId': {
      id: '/destinos/$destinoId'
      path: '/$destinoId'
      fullPath: '/destinos/$destinoId'
      preLoaderRoute: typeof DestinosDestinoIdRouteImport
      parentRoute: typeof DestinosRouteRoute
    }
    '/_protected/viajes': {
      id: '/_protected/viajes'
      path: '/viajes'
      fullPath: '/viajes'
      preLoaderRoute: typeof ProtectedViajesRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/reservas': {
      id: '/_protected/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ProtectedReservasRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/perfil': {
      id: '/_protected/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof ProtectedPerfilRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/viajes/completados': {
      id: '/_protected/viajes/completados'
      path: '/completados'
      fullPath: '/viajes/completados'
      preLoaderRoute: typeof ProtectedViajesCompletadosRouteImport
      parentRoute: typeof ProtectedViajesRouteRoute
    }
    '/_protected/viajes/cancelados': {
      id: '/_protected/viajes/cancelados'
      path: '/cancelados'
      fullPath: '/viajes/cancelados'
      preLoaderRoute: typeof ProtectedViajesCanceladosRouteImport
      parentRoute: typeof ProtectedViajesRouteRoute
    }
    '/_protected/viajes/activos': {
      id: '/_protected/viajes/activos'
      path: '/activos'
      fullPath: '/viajes/activos'
      preLoaderRoute: typeof ProtectedViajesActivosRouteImport
      parentRoute: typeof ProtectedViajesRouteRoute
    }
    '/_protected/reservas/pago': {
      id: '/_protected/reservas/pago'
      path: '/pago'
      fullPath: '/reservas/pago'
      preLoaderRoute: typeof ProtectedReservasPagoRouteImport
      parentRoute: typeof ProtectedReservasRouteRoute
    }
    '/_protected/reservas/nave': {
      id: '/_protected/reservas/nave'
      path: '/nave'
      fullPath: '/reservas/nave'
      preLoaderRoute: typeof ProtectedReservasNaveRouteImport
      parentRoute: typeof ProtectedReservasRouteRoute
    }
    '/_protected/reservas/fechas': {
      id: '/_protected/reservas/fechas'
      path: '/fechas'
      fullPath: '/reservas/fechas'
      preLoaderRoute: typeof ProtectedReservasFechasRouteImport
      parentRoute: typeof ProtectedReservasRouteRoute
    }
    '/_protected/reservas/confirmacion': {
      id: '/_protected/reservas/confirmacion'
      path: '/confirmacion'
      fullPath: '/reservas/confirmacion'
      preLoaderRoute: typeof ProtectedReservasConfirmacionRouteImport
      parentRoute: typeof ProtectedReservasRouteRoute
    }
    '/_protected/reservas/cabina': {
      id: '/_protected/reservas/cabina'
      path: '/cabina'
      fullPath: '/reservas/cabina'
      preLoaderRoute: typeof ProtectedReservasCabinaRouteImport
      parentRoute: typeof ProtectedReservasRouteRoute
    }
    '/_protected/perfil/seguridad': {
      id: '/_protected/perfil/seguridad'
      path: '/seguridad'
      fullPath: '/perfil/seguridad'
      preLoaderRoute: typeof ProtectedPerfilSeguridadRouteImport
      parentRoute: typeof ProtectedPerfilRouteRoute
    }
    '/_protected/perfil/resumen': {
      id: '/_protected/perfil/resumen'
      path: '/resumen'
      fullPath: '/perfil/resumen'
      preLoaderRoute: typeof ProtectedPerfilResumenRouteImport
      parentRoute: typeof ProtectedPerfilRouteRoute
    }
    '/_protected/admin/resumen': {
      id: '/_protected/admin/resumen'
      path: '/resumen'
      fullPath: '/admin/resumen'
      preLoaderRoute: typeof ProtectedAdminResumenRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/planetas': {
      id: '/_protected/admin/planetas'
      path: '/planetas'
      fullPath: '/admin/planetas'
      preLoaderRoute: typeof ProtectedAdminPlanetasRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/pasajeros': {
      id: '/_protected/admin/pasajeros'
      path: '/pasajeros'
      fullPath: '/admin/pasajeros'
      preLoaderRoute: typeof ProtectedAdminPasajerosRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/naves': {
      id: '/_protected/admin/naves'
      path: '/naves'
      fullPath: '/admin/naves'
      preLoaderRoute: typeof ProtectedAdminNavesRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminNavesRoute: typeof ProtectedAdminNavesRoute
  ProtectedAdminPasajerosRoute: typeof ProtectedAdminPasajerosRoute
  ProtectedAdminPlanetasRoute: typeof ProtectedAdminPlanetasRoute
  ProtectedAdminResumenRoute: typeof ProtectedAdminResumenRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminNavesRoute: ProtectedAdminNavesRoute,
  ProtectedAdminPasajerosRoute: ProtectedAdminPasajerosRoute,
  ProtectedAdminPlanetasRoute: ProtectedAdminPlanetasRoute,
  ProtectedAdminResumenRoute: ProtectedAdminResumenRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedPerfilRouteRouteChildren {
  ProtectedPerfilResumenRoute: typeof ProtectedPerfilResumenRoute
  ProtectedPerfilSeguridadRoute: typeof ProtectedPerfilSeguridadRoute
}

const ProtectedPerfilRouteRouteChildren: ProtectedPerfilRouteRouteChildren = {
  ProtectedPerfilResumenRoute: ProtectedPerfilResumenRoute,
  ProtectedPerfilSeguridadRoute: ProtectedPerfilSeguridadRoute,
}

const ProtectedPerfilRouteRouteWithChildren =
  ProtectedPerfilRouteRoute._addFileChildren(ProtectedPerfilRouteRouteChildren)

interface ProtectedReservasRouteRouteChildren {
  ProtectedReservasCabinaRoute: typeof ProtectedReservasCabinaRoute
  ProtectedReservasConfirmacionRoute: typeof ProtectedReservasConfirmacionRoute
  ProtectedReservasFechasRoute: typeof ProtectedReservasFechasRoute
  ProtectedReservasNaveRoute: typeof ProtectedReservasNaveRoute
  ProtectedReservasPagoRoute: typeof ProtectedReservasPagoRoute
}

const ProtectedReservasRouteRouteChildren: ProtectedReservasRouteRouteChildren =
  {
    ProtectedReservasCabinaRoute: ProtectedReservasCabinaRoute,
    ProtectedReservasConfirmacionRoute: ProtectedReservasConfirmacionRoute,
    ProtectedReservasFechasRoute: ProtectedReservasFechasRoute,
    ProtectedReservasNaveRoute: ProtectedReservasNaveRoute,
    ProtectedReservasPagoRoute: ProtectedReservasPagoRoute,
  }

const ProtectedReservasRouteRouteWithChildren =
  ProtectedReservasRouteRoute._addFileChildren(
    ProtectedReservasRouteRouteChildren,
  )

interface ProtectedViajesRouteRouteChildren {
  ProtectedViajesActivosRoute: typeof ProtectedViajesActivosRoute
  ProtectedViajesCanceladosRoute: typeof ProtectedViajesCanceladosRoute
  ProtectedViajesCompletadosRoute: typeof ProtectedViajesCompletadosRoute
}

const ProtectedViajesRouteRouteChildren: ProtectedViajesRouteRouteChildren = {
  ProtectedViajesActivosRoute: ProtectedViajesActivosRoute,
  ProtectedViajesCanceladosRoute: ProtectedViajesCanceladosRoute,
  ProtectedViajesCompletadosRoute: ProtectedViajesCompletadosRoute,
}

const ProtectedViajesRouteRouteWithChildren =
  ProtectedViajesRouteRoute._addFileChildren(ProtectedViajesRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedPerfilRouteRoute: typeof ProtectedPerfilRouteRouteWithChildren
  ProtectedReservasRouteRoute: typeof ProtectedReservasRouteRouteWithChildren
  ProtectedViajesRouteRoute: typeof ProtectedViajesRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedPerfilRouteRoute: ProtectedPerfilRouteRouteWithChildren,
  ProtectedReservasRouteRoute: ProtectedReservasRouteRouteWithChildren,
  ProtectedViajesRouteRoute: ProtectedViajesRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface DestinosRouteRouteChildren {
  DestinosDestinoIdRoute: typeof DestinosDestinoIdRoute
  DestinosIndexRoute: typeof DestinosIndexRoute
}

const DestinosRouteRouteChildren: DestinosRouteRouteChildren = {
  DestinosDestinoIdRoute: DestinosDestinoIdRoute,
  DestinosIndexRoute: DestinosIndexRoute,
}

const DestinosRouteRouteWithChildren = DestinosRouteRoute._addFileChildren(
  DestinosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  DestinosRouteRoute: DestinosRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
