import type { Reservation } from '@/app/types/Reservation'
import type { ReservationAdmin } from '@/features/admin/components/PassengersList'
import type { ReservationOld } from '@/features/profile/components/ReservationCard'

export const mockReservationsNew: Reservation[] = [
  {
    id: 'res-001',
    userId: '1',
    planetId: '3',
    shipId: 'starweaver',
    departureDate: '2025-12-15',
    returnDate: '2025-12-22',
    cabinClass: 'Lujo',
    status: 'confirmed',
    totalCost: 30000,
  },
  {
    id: 'res-002',
    userId: '2',
    planetId: '1',
    shipId: 'void-runner',
    departureDate: '2025-11-28',
    returnDate: '2025-12-05',
    cabinClass: 'Estándar',
    status: 'completed',
    totalCost: 25000,
  },
  {
    id: 'res-003',
    userId: '2',
    planetId: '3',
    shipId: 'void-runner',
    departureDate: '2025-11-28',
    returnDate: '2025-12-05',
    cabinClass: 'Estándar',
    status: 'cancelled',
    totalCost: 25000,
  },
  {
    id: 'res-004',
    userId: '1',
    planetId: '1',
    shipId: 'nebula-dream',
    departureDate: '2025-10-10',
    returnDate: '2025-10-17',
    cabinClass: 'Lujo',
    status: 'in_transit',
    totalCost: 40000,
  },
]

export const mockReservations: ReservationOld[] = [
  {
    id: 'RES-001',
    destination: 'Kepler-442b',
    departureDate: '2024-12-15',
    returnDate: '2024-12-22',
    status: 'confirmed',
    ship: 'Stellar Voyager',
    cabin: 'Premium',
  },
  {
    id: 'RES-002',
    destination: 'Proxima Centauri b',
    departureDate: '2024-11-28',
    returnDate: '2024-12-05',
    status: 'completed',
    ship: 'Galaxy Explorer',
    cabin: 'Lujo Imperial',
  },
  {
    id: 'RES-003',
    destination: 'TRAPPIST-1e',
    departureDate: '2025-01-10',
    returnDate: '2025-01-17',
    status: 'in_transit',
    ship: 'Nebula Cruiser',
    cabin: 'Económica',
  },
  {
    id: 'RES-004',
    destination: 'Gliese 667Cc',
    departureDate: '2025-02-20',
    returnDate: '2025-02-27',
    status: 'cancelled',
    ship: 'Cosmic Odyssey',
    cabin: 'Estándar',
  },
]

export const mockReservationsAdmin: ReservationAdmin[] = [
  {
    id: 'res-001',
    planetId: 'kepler-442b',
    shipId: 'starweaver',
    departureDate: '2025-12-15',
    returnDate: '2025-12-22',
    passengers: 2,
    cabinClass: 'Lujo',
    status: 'confirmed',
    totalCost: 30000,
  },
  {
    id: 'res-002',
    planetId: 'trappist-1e',
    shipId: 'void-runner',
    departureDate: '2025-11-28',
    returnDate: '2025-12-05',
    passengers: 1,
    cabinClass: 'Estándar',
    status: 'completed',
    totalCost: 25000,
  },
  {
    id: 'res-003',
    planetId: 'gliese-667cc',
    shipId: 'void-runner',
    departureDate: '2025-11-28',
    returnDate: '2025-12-05',
    passengers: 4,
    cabinClass: 'Estándar',
    status: 'cancelled',
    totalCost: 25000,
  },
  {
    id: 'res-004',
    planetId: 'proxima-centauri-b',
    shipId: 'nebula-dream',
    departureDate: '2025-10-10',
    returnDate: '2025-10-17',
    passengers: 3,
    cabinClass: 'Lujo',
    status: 'in_transit',
    totalCost: 40000,
  },
]
